image: rocker/tidyverse

stages:
- build
- install R packages

variables:
  RENV_CONFIG_REPOS_OVERRIDE: "http://cran.r-project.org"
  RENV_PATHS_CACHE: ${CI_PROJECT_DIR}/cache
  RENV_PATHS_LIBRARY: ${CI_PROJECT_DIR}/renv/library

cache:
  key: ${CI_JOB_NAME}
  paths:
    - ${RENV_PATHS_CACHE}
    - ${RENV_PATHS_LIBRARY}

docker-build:
  # Official docker image.
  image: docker:latest
  stage: build
  services:
    - docker:dind
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE" .
    - docker push "$CI_REGISTRY_IMAGE"
  only:
    - master

install-R-packages:
  stage: install R packages
  script:
  - R -e 'renv::restore(packages = "renv")' # load from renv library instead of rocker container
  - R -e 'renv::settings$snapshot.type("simple")' #https://github.com/rstudio/renv/issues/143
  - R -e 'renv::restore()'
  - R -e 'library(caret)'
  - R -e 'library(pacman)'