---
title: "Cryptocurrency Research"
date: '`r paste("Last Updated:<br/>",Sys.time())`'
site: bookdown::bookdown_site
documentclass: book
bibliography:
- book.bib
- packages.bib
- main.bib
biblio-style: apalike
link-citations: yes
---

# Introduction {#introduction}

```{r initialSetup, message=FALSE, warning=FALSE, include=F}
library(bookdown)
library(knitr)
# tidy code
#knitr::opts_chunk$set(tidy = TRUE)
# to try to fix issue with ggplotly() not showing htmlwidget properly
knitr::opts_chunk$set(widgetframe_widgets_dir = 'widgets' )
# Get rid of messages and warnings
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
# Try getting rid of extra unwanted outputs
knitr::opts_knit$set(progress=FALSE, verbose = FALSE)
# Source gs_key.R
#source("gs_key.R")
```

**(this book is a work in progress and is NOT ready)**

## What will I learn?

-   In this tutorial you will primarily learn about tools for the R programming language developed by [RStudio](https://rstudio.com/) and more specifically the [tidyverse](https://www.tidyverse.org/). If you are not familiar with these open source products, don't worry. We'll introduce these throughout the tutorial as needed.

-   The focus of the tutorial is on supervised machine learning, a process for building models that can predict future events, such as cryptocurrency prices. You will learn how to use the [`caret`](https://topepo.github.io/caret/index.html) package to make many different predictive models, and tools to evaluate their performance.

-   You will learn how to perform "group by" operations on your data using the [`dplyr`](https://dplyr.tidyverse.org/) package.

-   You will be exposed to some very useful data pre-processing R packages, including [`skimr`](https://github.com/ropensci/skimr), [`janitor`](https://garthtarr.github.io/meatR/janitor.html) and [`anytime`](http://dirk.eddelbuettel.com/code/anytime.html).

-   You will learn about some powerful [extensions to the ggplot2 visualization framework](https://exts.ggplot2.tidyverse.org/).

-   You will gain a better understanding of the steps involved in any supervised machine learning process, as well considerations you might need to keep in mind based on your specific data and the way you plan on acting on the predictions you have made. Each problem comes with a unique set of challenges, but there are steps that are necessary in creating any supervised machine learning model, and questions you should ask yourself regardless of the specific problem at hand.

<!-- For example, regardless of what you may be predicting, you need to make sure you are only using information that you would have readily available when it is time to make a new prediction.  -->

<!-- Note/Reminder, delete: Another example here would be keeping in mind the way you plan on actually using the predictions to take specific actions and how beneficial it is to maintain that perspective. -->

-   You will also learn a little about cryptocurrencies themselves, but **this is not a tutorial around blockchain itself or trading**.

## Before Getting Started

**There are two different versions of this tutorial, one high-level, accessible version and one detailed, code-heavy version. We recommend you start with the high-level version of the tutorial (\#1 below):**

1.  [The high-level version of this tutorial](https://cryptocurrencyresearch.org/high-level/) simplifies the supervised machine learning process as much as possible and provides a high-level framework that can be used for most supervised learning problems. When following along with this example, the results will be completely reproducible and the document is static and does not update over time. Even if your intent is to appropriate all the knowledge of the detailed tutorial, consider doing this tutorial first.

2.  The detailed tutorial is the document you are currently looking at, and is a full example showing one possible approach to making predictions on the cryptocurrency markets. Here we discuss the nuances that are specific to our data and problem. We focus on the supervised machine learning process and modeling many cryptocurrencies at once rather than real trades on these markets. This entire document and results are updated twice daily with the latest data.

## Who is this example for?

Are you a Bob, Hosung, or Jessica? This section provides more information on how to proceed with this tutorial.

-   **Bob (beginner)**: Bob is someone who understands the idea of predictive analytics at a high level and has heard of cryptocurrencies and is interested in learning more about both, but he has never used R. Bob would want to first [learn the basics of the R programming language](https://predictcrypto.org/r-basics-tutorial). Afterwards, like Hosung, he might decide to [opt for the more high-level version of this tutorial](https://cryptocurrencyresearch.org/high-level/).

    -   Bob might benefit from the book ["R for Data Science"](https://r4ds.had.co.nz/) and DataCamp's free ["Introduction to R"](https://www.datacamp.com/courses/free-introduction-to-r) course are great resources as well. Both are available for free online.

-   **Hosung (intermediate)**: Hosung is a statistician who learned to use R 10 years ago. He has heard of the tidyverse, but doesn't regularly use it in his work and he usually sticks to base R as his preference. Hosung should review the example explaining the pipe operator and the tidyverse [when it comes up in the next section](https://cryptocurrencyresearch.org/setup.html#tidy-example). Hosung does not care much for cryptocurrencies specifically, but is interested in learning new tools to use for his work in R and getting some useful boilerplate code. Hosung would want to start with the [**high-level version of this tutorial**](https://cryptocurrencyresearch.org/high-level/) and later return to the [**detailed tutorial**](https://cryptocurrencyresearch.org/index.html#introduction).

-   **Jessica (expert)**: Jessica is a business analyst who has experience with both R and the Tidyverse and uses the pipe operator (%\>%) regularly. Jessica should [**move onto the next section**](#introduction) for the detailed tutorial.

## Format Notes

-   You can hide the sidebar on the left by pressing the ***s*** key on your keyboard.

-   When the code is `highlighted this way`, that means we are referencing an R object of some kind. This will usually be an object in the R session like a dataset, but functions and packages are highlighted in the same way.

-   The cryptocurrency data was chosen to produce results that change over time and because these markets don't have any downtime (unlike the stock market).

## Plan of Attack

How will we generate predictive models to predict cryptocurrency prices? At a high level, here are the steps we will be taking:

1. [Setup guide](#setup). Installation guide on getting the tools used installed on your machine.

2. [Explore data](#explore-data). What ***is*** the data we are working with? How "good" is the "quality"? 

3. [Prepare the data](#data-prep). Make adjustments to "clean" the data based on the findings from the previous section to avoid running into problems when making models to make predictions.

4. [Visualize the data](#visualization). Visualizing the data can be an effective way to understand relationships, trends and outliers before creating predictive models.

5. [Make predictive models](#predictive-modeling). Now we are ready to take the data available to us and use it to make predictive models that can be used to make predictions about future price movements using the latest data.

6. [Evaluate the performance of the models](#evaluate-model-performance). Before we can use the predictive models to make predictions on the latest data, we need to understand how well we expect them to perform, which is also essential in detecting issues.


## Disclaimer

```{block2, note-disclaimer, type='rmdimportant'}
This tutorial is made available for learning and educational purposes only and the information to follow does not constitute trading advice in any way shape or form. We avoid giving any advice when it comes to trading strategies, as this is a very complex ecosystem that is out of the scope of this tutorial; we make no attempt in this regard, and if this, rather than data science, is your interest, your time would be better spent following a different tutorial that aims to answer those questions.
```

<!-- REMEMBER OTHER SPECIAL BLOCK TYPE IS CALLED "rmdcaution" USE THESE TO DRAW ATTENTION TO ANYTHING IMPORTANT! -->
