name: Run Crypto Tutorial
on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-10.15
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install pandoc and pandoc citeproc and xquartz
        run: |
          brew install pandoc
          brew install pandoc-citeproc
          brew cask install xquartz
          wget https://dl.bintray.com/xquartz/downloads/XQuartz-2.7.11.dmg
          sudo hdiutil attach XQuartz-2.7.11.dmg
          sudo installer -package /Volumes/XQuartz-2.7.11/XQuartz.pkg -target / 
      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-3-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-3-
      - name: Install Packages
        run: |-
          Rscript -e "install.packages('renv')"
          Rscript -e 'renv::consent(provided = TRUE)'
          Rscript -e "renv::restore()"
          Rscript -e "install.packages(c('knitr','bookdown','deepnet','devtools'))"
          Rscript -e "#devtools::install_github('tylermorganwall/rayshader')"
          Rscript -e "#devtools::install_github('cran/rgl')"
          Rscript -e "#devtools::install_github('ropensci/magick')"
      - name: Render Book
        run: |-
          Rscript -e "bookdown::render_book('index.Rmd')"
      - name: Commit and push files
        run: |
          git config --local user.email "ries9112@colorado.edu"
          git config --local user.name "ries9112"
          git add .
          git commit -m "Add html output from CI process" -a
          git push https://ries9112:${{secrets.GITHUB_TOKEN}}@github.com/ries9112/cryptocurrencyresearch-org.git HEAD:main --force
