name: Run Crypto Tutorial
on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - name: Install pandoc and pandoc citeproc
        run: |
          brew install pandoc
          brew install pandoc-citeproc
      - name: Cache R packages
        if: runner.os != 'Windows'
        uses: actions/cache@v1
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-r-${{ matrix.config.r }}-3-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-r-${{ matrix.config.r }}-3-
      - name: Install Packages and Run Script
        run: |-
          Rscript -e "install.packages('renv')"
          Rscript -e "renv::restore()"
          Rscript -e "install.packages(c('knitr','bookdown','deepnet','devtools'))"
          Rscript -e "#devtools::install_github('tylermorganwall/rayshader')"
          Rscript -e "#devtools::install_github('cran/rgl')"
          Rscript -e "#devtools::install_github('ropensci/magick')"
          Rscript -e "#rmarkdown::render('test_script_tutorial.Rmd')"
